config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  
  resources :playlists do 
    resources :songs 
  end 

  resources :artists do 
    resources :songs 
  end 

  resources :albums do
    resources :songs 
  end 

  resources :songs 


end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artists 
    has_many :songs, :through => :artists 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums 
    has_many :songs, :through => :albums 
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :songs 
    has_many :artists, :through => :songs 
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :album
    belongs_to :artist
    belongs_to :playlist 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_artist 
  before_action :set_album, only: [:show, :update, :edit, :destroy]

  def index
    @albums = @artist.albums 
  end

  def show
  end

  def new
    @album = @artists.album.new
    render "form" 
  end

  def edit
    render "form" 
  end

  def create
    @album = @artist.albums.new(album_params)
    if @album.save
      redirect_to [@artist, @album]
    else
      render :new
    end
  end

  def update
    if @album.update(album_params)
      redirect_to [@artist, @album]
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to artist_albums_path
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
    
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  before_action :set_artist, only: [:show, :update, :edit, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render "form" 
  end

  def edit
    render "form" 
  end

  def create
    @artist = Artist.new(artist_params)
    
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artist_path
  end

  private
    
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home 
    end 
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :update, :edit, :destroy]

  def index
    @playlists = Playlist.all
  end

  def show
  end

  def new
    @playlist = Playlist.new
    render "form" 
  end

  def edit
    render "form"
  end

  def create
    @playlist = Playlist.new(playlist_params)
    
    if @playlist.save
      redirect_to playlists_path
    else
      render :new
    end
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlist_path
  end

  private
    
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    def playlist_params 
      params.require(:playlist).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  before_action :set_song, only: [:show, :update, :edit, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
    render "form"
  end

  def edit
    render "form" 
  end

  def create
    @song = Song.new(song_params)
    
    if @song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to song_path
  end

  private
    
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/form.html.erb
<h1><%= @album.id ? "Edit Album" : "Create Album" %></h1>
<hr/>

<%= form_for @album do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
    <br />
    <%= f.submit %>  
<% end %> 

app/views/albums/index.html.erb
<h1>Click an Album To View Contents</h1>
<%= link_to 'Create a new album', new_artist_album_path(@artist) %>
<ul>
  <% @albums.each do |album| %>
    <li><%= link_to album.name, [@artist, @album] %></li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/form.html.erb
<h1><%= @artist.id ? "Edit Artist" : "Create Artist" %></h1>
<hr/>

<%= form_for @artist do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
    <br />
    <%= f.submit %>  
<% end %> 

app/views/artists/index.html.erb
<h1>Click an Artist To View Albums</h1>
<%= link_to 'Create a new artist', new_artist_path %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist %></li>
  <% end %>
</ul>

<hr />
<p>What would you like to do?</p>
<%= link_to 'View Albums', artist_albums_path(@artist) %>
<br />
<%= link_to 'Edit Artist', edit_artist_path(@artist) %>
<br />
<%= link_to 'Delete Artist', @artist, method: :delete %>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/home/home.html.erb
<h1>Library</h1> 
<%= link_to "Playlists", playlists_path %>
</br>
<%= link_to "Albums", albums_path %>
</br>
<%= link_to "Artists", artists_path %>
</br>
<%= link_to "Songs", songs_path %> 

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Playlists', playlists_path %> 
<%= link_to 'Albums', albums_path %>
<%= link_to 'Artists', artists_path %>
<%= link_to 'Songs', songs_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

app/views/playlists/form.html.erb
<h1><%= @playlist.id ? "Edit Playlist" : "Create Playlist" %></h1>
<hr/>

<%= form_for @playlist do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
    <br />
    <%= f.submit %>  
<% end %> 

app/views/playlists/index.html.erb
<h1>Click a Playlist To View Contents</h1>
<%= link_to 'Create a new Playlist', new_playlist_path %>
<ul>
  <% @playlists.each do |playlist| %>
    <li><%= link_to playlist.name %></li>
  <% end %>
</ul>

app/views/playlists/new.html.erb
<h1>Playlists#new</h1>
<p>Find me in app/views/playlists/new.html.erb</p>

app/views/playlists/show.html.erb
<h1>Playlists#show</h1>
<p>Find me in app/views/playlists/show.html.erb</p>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/form.html.erb
<h1><%= @song.id ? "Edit Song" : "Create Song" %></h1>
<hr/>

<%= form_for @song do |f| %> 
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true %>
    <br />
    <%= f.submit %>  
<% end %> 

app/views/songs/index.html.erb
<h1>Click a Song To View Contents</h1>
<%= link_to 'Create a new song', new_song_path %>
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.name %></li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>